name: Version Management

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: 'Part of version to bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bump-my-version

    - name: Configure Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Bump version
      id: bump
      run: |
        bump-my-version bump ${{ github.event.inputs.version_part }}

    - name: Get new version
      id: get_version
      run: |
        echo "VERSION=$(grep -m 1 'current_version' pyproject.toml | sed -r 's/^current_version = \"(.*)\"$/\1/')" >> $GITHUB_OUTPUT

    - name: Push changes
      run: |
        git push
        git push --tags 